spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssoAuth
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3600
    lettuce:
      pool:
        max-idle: 10   #最大空闲连接
        max-active: 8   # 最大连接数
        max-wait: -1  # 最大等待时间（使用负值表示没有限制）
        min-idle: 0   # 连接池最小空闲连接
      shutdown-timeout: 100 # 关闭超时时间

auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: client_001
  clientSecret: 123456
  cookieDomain: mygallop.cn
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/keystore.jks
    secret: gallop123
    alias: mytest
    password: 123456


user:
  service:
    version: 1.0.0